# Set default path
SRC_PATH ?= $(PWD)
BLD_PATH ?= $(SRC_PATH)/../build
DEPLOYDIR ?= $(SRC_PATH)/../deploy
FIPTOOLDIR ?= $(SRC_PATH)/..

BL31_DEPLOYDIR     ?= $(DEPLOYDIR)/bl31
BL32_DEPLOYDIR     ?= $(DEPLOYDIR)/bl32
FWCONFIG_DEPLOYDIR ?= $(DEPLOYDIR)/fwconfig
FWDDR_DEPLOYDIR    ?= $(DEPLOYDIR)/ddr

# Configure default TF-A features
TF_A_ENABLE_BL31 ?= 1
TF_A_ENABLE_DEBUG_WRAPPER ?= 1
TF_A_ENABLE_FWDDR ?= 1

# Set default TF-A config
TF_A_CONFIG ?= optee-emmc optee-sdcard optee-programmer-usb

# Set default FIP config
FIP_CONFIG ?= optee-emmc optee-sdcard optee-programmer-usb

# Default TF-A overall settings to null
TF_A_BINARY ?=
TF_A_DEVICETREE ?=
TF_A_MAKE_TARGET ?=
TF_A_EXTRA_OPTFLAGS ?=

# Default TF-A metadata template
TF_A_METADATA_JSON ?= $(SRC_PATH)/

# Init default config settings
TF_A_DEVICETREE_INTERNAL_optee-emmc ?= stm32mp257d-atk-ddr-1GB stm32mp257d-atk-ddr-2GB
TF_A_DEVICETREE_EXTERNAL_optee-emmc ?= stm32mp257f-ev1-ca35tdcid-ostl-m33-examples stm32mp257f-ev1-ca35tdcid-ostl stm32mp257f-dk-ca35tdcid-ostl-m33-examples stm32mp257f-dk-ca35tdcid-ostl
TF_A_DEVICETREE_optee-emmc = $(TF_A_DEVICETREE_INTERNAL_optee-emmc) $(if $(EXTDT_DIR),$(TF_A_DEVICETREE_EXTERNAL_optee-emmc))
TF_A_EXTRA_OPTFLAGS_optee-emmc ?= SPD=opteed PSA_FWU_SUPPORT=1 STM32MP_EMMC=1
TF_A_BINARY_optee-emmc ?= tf-a
TF_A_MAKE_TARGET_optee-emmc ?= all
# Init default config settings
TF_A_DEVICETREE_INTERNAL_optee-nor ?=  stm32mp257f-ev1 
TF_A_DEVICETREE_EXTERNAL_optee-nor ?= 
TF_A_DEVICETREE_optee-nor = $(TF_A_DEVICETREE_INTERNAL_optee-nor) $(if $(EXTDT_DIR),$(TF_A_DEVICETREE_EXTERNAL_optee-nor))
TF_A_EXTRA_OPTFLAGS_optee-nor ?=  SPD=opteed PSA_FWU_SUPPORT=1 STM32MP_SPI_NOR=1 STM32MP_FORCE_MTD_START_OFFSET=0x00100000
TF_A_BINARY_optee-nor ?= tf-a
TF_A_MAKE_TARGET_optee-nor ?=  all
# Init default config settings
TF_A_DEVICETREE_INTERNAL_optee-sdcard ?= stm32mp257d-atk-ddr-1GB stm32mp257d-atk-ddr-2GB
TF_A_DEVICETREE_EXTERNAL_optee-sdcard ?= stm32mp257f-ev1-ca35tdcid-ostl-m33-examples-sram stm32mp257f-ev1-ca35tdcid-ostl-m33-examples stm32mp257f-ev1-ca35tdcid-ostl stm32mp257f-dk-ca35tdcid-ostl-m33-examples stm32mp257f-dk-ca35tdcid-ostl
TF_A_DEVICETREE_optee-sdcard = $(TF_A_DEVICETREE_INTERNAL_optee-sdcard) $(if $(EXTDT_DIR),$(TF_A_DEVICETREE_EXTERNAL_optee-sdcard))
TF_A_EXTRA_OPTFLAGS_optee-sdcard ?=  SPD=opteed PSA_FWU_SUPPORT=1 STM32MP_SDMMC=1
TF_A_BINARY_optee-sdcard ?= tf-a
TF_A_MAKE_TARGET_optee-sdcard ?=  all
# Init default config settings
TF_A_DEVICETREE_INTERNAL_optee-programmer-usb ?= stm32mp257d-atk-ddr-1GB stm32mp257d-atk-ddr-2GB
TF_A_DEVICETREE_EXTERNAL_optee-programmer-usb ?= stm32mp257f-ev1-ca35tdcid-ostl-m33-examples stm32mp257f-ev1-ca35tdcid-ostl stm32mp257f-dk-ca35tdcid-ostl-m33-examples stm32mp257f-dk-ca35tdcid-ostl stm32mp257f-ev1-ca35tdcid-ostl-m33-examples-sram
TF_A_DEVICETREE_optee-programmer-usb = $(TF_A_DEVICETREE_INTERNAL_optee-programmer-usb) $(if $(EXTDT_DIR),$(TF_A_DEVICETREE_EXTERNAL_optee-programmer-usb))
TF_A_EXTRA_OPTFLAGS_optee-programmer-usb ?=  SPD=opteed STM32MP_USB_PROGRAMMER=1
TF_A_BINARY_optee-programmer-usb ?= tf-a
TF_A_MAKE_TARGET_optee-programmer-usb ?=  all dtbs
# Init default config settings
TF_A_DEVICETREE_INTERNAL_optee-programmer-uart ?=  stm32mp235f-dk stm32mp257f-dk stm32mp257f-ev1 
TF_A_DEVICETREE_EXTERNAL_optee-programmer-uart ?= stm32mp257f-ev1-ca35tdcid-ostl-m33-examples stm32mp257f-ev1-ca35tdcid-ostl stm32mp257f-dk-ca35tdcid-ostl-m33-examples stm32mp257f-dk-ca35tdcid-ostl stm32mp257f-ev1-ca35tdcid-ostl-m33-examples-sram
TF_A_DEVICETREE_optee-programmer-uart = $(TF_A_DEVICETREE_INTERNAL_optee-programmer-uart) $(if $(EXTDT_DIR),$(TF_A_DEVICETREE_EXTERNAL_optee-programmer-uart))
TF_A_EXTRA_OPTFLAGS_optee-programmer-uart ?=  SPD=opteed STM32MP_UART_PROGRAMMER=1
TF_A_BINARY_optee-programmer-uart ?= tf-a
TF_A_MAKE_TARGET_optee-programmer-uart ?=  all dtbs
# Init default config settings
TF_A_DEVICETREE_INTERNAL_opteemin-emmc ?=  stm32mp235f-dk stm32mp257f-dk stm32mp257f-ev1 
TF_A_DEVICETREE_EXTERNAL_opteemin-emmc ?= stm32mp257f-ev1-ca35tdcid-ostl-m33-examples stm32mp257f-ev1-ca35tdcid-ostl stm32mp257f-dk-ca35tdcid-ostl-m33-examples stm32mp257f-dk-ca35tdcid-ostl
TF_A_DEVICETREE_opteemin-emmc = $(TF_A_DEVICETREE_INTERNAL_opteemin-emmc) $(if $(EXTDT_DIR),$(TF_A_DEVICETREE_EXTERNAL_opteemin-emmc))
TF_A_EXTRA_OPTFLAGS_opteemin-emmc ?=  SPD=opteed PSA_FWU_SUPPORT=1 STM32MP_EMMC=1
TF_A_BINARY_opteemin-emmc ?= tf-a
TF_A_MAKE_TARGET_opteemin-emmc ?=  all
# Init default config settings
TF_A_DEVICETREE_INTERNAL_opteemin-nor ?=  stm32mp257f-ev1 
TF_A_DEVICETREE_EXTERNAL_opteemin-nor ?= 
TF_A_DEVICETREE_opteemin-nor = $(TF_A_DEVICETREE_INTERNAL_opteemin-nor) $(if $(EXTDT_DIR),$(TF_A_DEVICETREE_EXTERNAL_opteemin-nor))
TF_A_EXTRA_OPTFLAGS_opteemin-nor ?=  SPD=opteed PSA_FWU_SUPPORT=1 STM32MP_SPI_NOR=1 STM32MP_FORCE_MTD_START_OFFSET=0x00100000
TF_A_BINARY_opteemin-nor ?= tf-a
TF_A_MAKE_TARGET_opteemin-nor ?=  all
# Init default config settings
TF_A_DEVICETREE_INTERNAL_opteemin-sdcard ?=  stm32mp235f-dk stm32mp257f-dk stm32mp257f-ev1 
TF_A_DEVICETREE_EXTERNAL_opteemin-sdcard ?= stm32mp257f-ev1-ca35tdcid-ostl-m33-examples-sram stm32mp257f-ev1-ca35tdcid-ostl-m33-examples stm32mp257f-ev1-ca35tdcid-ostl stm32mp257f-dk-ca35tdcid-ostl-m33-examples stm32mp257f-dk-ca35tdcid-ostl
TF_A_DEVICETREE_opteemin-sdcard = $(TF_A_DEVICETREE_INTERNAL_opteemin-sdcard) $(if $(EXTDT_DIR),$(TF_A_DEVICETREE_EXTERNAL_opteemin-sdcard))
TF_A_EXTRA_OPTFLAGS_opteemin-sdcard ?=  SPD=opteed PSA_FWU_SUPPORT=1 STM32MP_SDMMC=1
TF_A_BINARY_opteemin-sdcard ?= tf-a
TF_A_MAKE_TARGET_opteemin-sdcard ?=  all
# Init default config settings
TF_A_DEVICETREE_INTERNAL_opteemin-programmer-usb ?=  stm32mp235f-dk stm32mp257f-dk stm32mp257f-ev1 
TF_A_DEVICETREE_EXTERNAL_opteemin-programmer-usb ?= stm32mp257f-ev1-ca35tdcid-ostl-m33-examples stm32mp257f-ev1-ca35tdcid-ostl stm32mp257f-dk-ca35tdcid-ostl-m33-examples stm32mp257f-dk-ca35tdcid-ostl stm32mp257f-ev1-ca35tdcid-ostl-m33-examples-sram
TF_A_DEVICETREE_opteemin-programmer-usb = $(TF_A_DEVICETREE_INTERNAL_opteemin-programmer-usb) $(if $(EXTDT_DIR),$(TF_A_DEVICETREE_EXTERNAL_opteemin-programmer-usb))
TF_A_EXTRA_OPTFLAGS_opteemin-programmer-usb ?=  SPD=opteed STM32MP_USB_PROGRAMMER=1
TF_A_BINARY_opteemin-programmer-usb ?= tf-a
TF_A_MAKE_TARGET_opteemin-programmer-usb ?=  all dtbs
# Init default config settings
TF_A_DEVICETREE_INTERNAL_opteemin-programmer-uart ?=  stm32mp235f-dk stm32mp257f-dk stm32mp257f-ev1 
TF_A_DEVICETREE_EXTERNAL_opteemin-programmer-uart ?= stm32mp257f-ev1-ca35tdcid-ostl-m33-examples stm32mp257f-ev1-ca35tdcid-ostl stm32mp257f-dk-ca35tdcid-ostl-m33-examples stm32mp257f-dk-ca35tdcid-ostl stm32mp257f-ev1-ca35tdcid-ostl-m33-examples-sram
TF_A_DEVICETREE_opteemin-programmer-uart = $(TF_A_DEVICETREE_INTERNAL_opteemin-programmer-uart) $(if $(EXTDT_DIR),$(TF_A_DEVICETREE_EXTERNAL_opteemin-programmer-uart))
TF_A_EXTRA_OPTFLAGS_opteemin-programmer-uart ?=  SPD=opteed STM32MP_UART_PROGRAMMER=1
TF_A_BINARY_opteemin-programmer-uart ?= tf-a
TF_A_MAKE_TARGET_opteemin-programmer-uart ?=  all dtbs

# Reset default variables
LDFLAGS =
CFLAGS =
CPPFLAGS =
CC =
CPP =
AS =
AR =
LD =
NM =
# Define default make options
EXTRA_OEMAKE ?=  PLAT=stm32mp2 ARCH=aarch64 ARM_ARCH_MAJOR=8 CROSS_COMPILE=aarch64-ostl-linux- DEBUG=1 LOG_LEVEL=40 TFA_EXTERNAL_DT=$(EXTDT_DIR)/tf-a       

# Display TF-A config details
define tf-configs
	echo "  $(1)" ; \
	echo "    with device tree : $(if $(TF_A_DEVICETREE),$(TF_A_DEVICETREE),$(TF_A_DEVICETREE_$(1)))" ; \
	echo "    extra optionflags: $(if $(TF_A_EXTRA_OPTFLAGS),$(TF_A_EXTRA_OPTFLAGS),$(TF_A_EXTRA_OPTFLAGS_$(1)))" ; \
	echo "    binary basename  : $(if $(TF_A_BINARY),$(TF_A_BINARY),$(TF_A_BINARY_$(1)) (TF_A_BINARY_$(1)))" ; \
	echo "    tf-a build target: $(if $(TF_A_MAKE_TARGET),$(TF_A_MAKE_TARGET),$(TF_A_MAKE_TARGET_$(1)))" ;
endef

# Configure TF-A make rules ( tf-<CONFIG>-<SOC>: <DEPS> )
define tf-rules
tf-$(1)-$(2): $3
	@$(foreach dt, $(if $(TF_A_DEVICETREE),$(TF_A_DEVICETREE),$(TF_A_DEVICETREE_$(1))), \
		$(if $(findstring $(2),$(dt)), \
			mkdir -p  $(BLD_PATH)/$(1)-$(dt); \
			touch $(BLD_PATH)/$(1)-$(dt)/$(dt)-sysram.txt ; \
			if [ "$(2)" = "stm32mp15" ]; then \
				(echo $(1) | grep "optee-" && echo "STM32MP1_OPTEE_IN_SYSRAM=1" > $(BLD_PATH)/$(1)-$(dt)/$(dt)-sysram.txt); \
			fi; \
			$(MAKE) $(EXTRA_OEMAKE) -C $(SRC_PATH) \
				BUILD_PLAT=$(BLD_PATH)/$(1)-$(dt) \
				DTB_FILE_NAME=$(dt).dtb \
				$(if $(TF_A_EXTRA_OPTFLAGS),$(TF_A_EXTRA_OPTFLAGS),$(TF_A_EXTRA_OPTFLAGS_$(1))) \
				`cat $(BLD_PATH)/$(1)-$(dt)/$(dt)-sysram.txt` \
				dtbs \
				$(shell echo $(2) | tr a-z A-Z)=1 || exit 1; \
			touch $(BLD_PATH)/$(1)-$(dt)/$(dt)-pmic1l_property.txt ; \
			(fdtdump "$(BLD_PATH)/$(1)-$(dt)/fdts/$(dt)-bl2.dtb" 2>/dev/null | grep -c "st,stpmic1l" || /bin/true) > $(BLD_PATH)/$(1)-$(dt)/$(dt)-pmic1l_node.txt; \
			if [ "`cat $(BLD_PATH)/$(1)-$(dt)/$(dt)-pmic1l_node.txt`" = "1" ]; then \
				(echo "STM32MP_STPMIC1L=1" > $(BLD_PATH)/$(1)-$(dt)/$(dt)-pmic1l_property.txt); \
			fi; \
			touch $(BLD_PATH)/$(1)-$(dt)/$(dt)-ddr_property.txt ; \
			if [ "$(TF_A_ENABLE_FWDDR)" = "1" ] ; then \
				if [ -f "$(BLD_PATH)/$(1)-$(dt)/fdts/$(dt)-bl2.dtb" ]; then \
					fdtget -l "$(BLD_PATH)/$(1)-$(dt)/fdts/$(dt)-bl2.dtb" /soc | grep ddr | head -n 1 > $(BLD_PATH)/$(1)-$(dt)/$(dt)-ddr_dtb_node.txt ; \
					(fdtget "$(BLD_PATH)/$(1)-$(dt)/fdts/$(dt)-bl2.dtb" /soc/`cat $(BLD_PATH)/$(1)-$(dt)/$(dt)-ddr_dtb_node.txt` st,mem-name) > $(BLD_PATH)/$(1)-$(dt)/$(dt)-ddr_property.txt ; \
					sed -i -e 's|^\(.*DDR[0-9]\).*| STM32MP_\1_TYPE=1 |' $(BLD_PATH)/$(1)-$(dt)/$(dt)-ddr_property.txt ; \
					sed -e 's|.*_\(.*DDR[0-9]\)_.*|\1|' $(BLD_PATH)/$(1)-$(dt)/$(dt)-ddr_property.txt | tr A-Z a-z > $(BLD_PATH)/$(1)-$(dt)/$(dt)-ddr_target.txt ; \
					if [ -f "$(FWDDR_DIR)/stm32mp2/`cat $(BLD_PATH)/$(1)-$(dt)/$(dt)-ddr_target.txt`_pmu_train.bin" ]; then \
						cp -f $(FWDDR_DIR)/stm32mp2/`cat $(BLD_PATH)/$(1)-$(dt)/$(dt)-ddr_target.txt`_pmu_train.bin $(BLD_PATH)/$(1)-$(dt)/ddr_pmu-$(dt).bin ; \
					fi ; \
				fi ; \
			fi ; \
			$(MAKE) $(EXTRA_OEMAKE) -C $(SRC_PATH) \
				BUILD_PLAT=$(BLD_PATH)/$(1)-$(dt) \
				DTB_FILE_NAME=$(dt).dtb \
				`cat $(BLD_PATH)/$(1)-$(dt)/$(dt)-sysram.txt` \
				`cat $(BLD_PATH)/$(1)-$(dt)/$(dt)-ddr_property.txt` \
				`cat $(BLD_PATH)/$(1)-$(dt)/$(dt)-pmic1l_property.txt` \
				$(if $(TF_A_EXTRA_OPTFLAGS),$(TF_A_EXTRA_OPTFLAGS),$(TF_A_EXTRA_OPTFLAGS_$(1))) \
				$(if $(TF_A_MAKE_TARGET),$(TF_A_MAKE_TARGET),$(TF_A_MAKE_TARGET_$(1))) \
				$(shell echo $(2) | tr a-z A-Z)=1 || exit 1; \
		,) \
	)
endef

# Configure TF-A deploy rules ( deploy-<CONFIG>-<SOC>: tf-<CONFIG>-<SOC> [$(3)=<BINARY>] )
define deploy-rules
deploy-$(1)-$(2): tf-$(1)-$(2)
	@mkdir -p $(DEPLOYDIR)
	@mkdir -p $(DEPLOYDIR)/debug
	@$(foreach dt, $(if $(TF_A_DEVICETREE),$(TF_A_DEVICETREE),$(TF_A_DEVICETREE_$(1))), \
		if [ -f "$(BLD_PATH)/$(1)-$(dt)/ddr_pmu-$(dt).bin" ]; then \
			mkdir -p $(FWDDR_DEPLOYDIR) ; \
			cp -f $(BLD_PATH)/$(1)-$(dt)/ddr_pmu-$(dt).bin $(FWDDR_DEPLOYDIR)/ ; \
		fi ; \
	)
	@$(foreach dt, $(if $(TF_A_DEVICETREE),$(TF_A_DEVICETREE),$(TF_A_DEVICETREE_$(1))), \
		if [ -f $(BLD_PATH)/$(1)-$(dt)/$(3)-$(dt).stm32 ]; then \
			cp -f $(BLD_PATH)/$(1)-$(dt)/$(3)-$(dt).stm32 $(DEPLOYDIR)/$(3)-$(dt)-$(1).stm32 ; \
			if [ "$(TF_A_ENABLE_DEBUG_WRAPPER)" = "1" ] ; then \
				stm32wrapper4dbg -s $(BLD_PATH)/$(1)-$(dt)/$(3)-$(dt).stm32 -d $(DEPLOYDIR)/debug/debug-$(3)-$(dt)-$(1).stm32 ; \
			fi ; \
		fi ; \
	)
	@$(foreach dt, $(if $(TF_A_DEVICETREE),$(TF_A_DEVICETREE),$(TF_A_DEVICETREE_$(1))), \
		if [ -f $(BLD_PATH)/$(1)-$(dt)/bl31.bin ] ; then \
			mkdir -p $(BL31_DEPLOYDIR) ; \
			cp -f $(BLD_PATH)/$(1)-$(dt)/bl31.bin $(BL31_DEPLOYDIR)/$(3)-bl31-$(dt)-$(1).bin ; \
			if [ -f $(BLD_PATH)/$(1)-$(dt)/fdts/$(dt)-bl31.dtb ]; then \
				cp -f $(BLD_PATH)/$(1)-$(dt)/fdts/$(dt)-bl31.dtb $(BL31_DEPLOYDIR)/$(dt)-bl31-$(1).dtb; \
			fi ; \
			if [ -f $(BLD_PATH)/$(1)-$(dt)/bl31/bl31.elf ]; then \
				mkdir -p $(BL31_DEPLOYDIR)/debug ; \
				cp -f $(BLD_PATH)/$(1)-$(dt)/bl31/bl31.elf $(BL31_DEPLOYDIR)/debug/$(3)-bl31-$(dt)-$(1).elf ; \
			fi ; \
		fi ; \
	)
	@$(foreach dt, $(if $(TF_A_DEVICETREE),$(TF_A_DEVICETREE),$(TF_A_DEVICETREE_$(1))), \
		if [ -f $(BLD_PATH)/$(1)-$(dt)/bl32.bin ] ; then \
			mkdir -p $(BL32_DEPLOYDIR) ; \
			cp -f $(BLD_PATH)/$(1)-$(dt)/bl32.bin $(BL32_DEPLOYDIR)/$(3)-bl32-$(2)-$(1).bin ; \
			if [ -f $(BLD_PATH)/$(1)-$(dt)/fdts/$(dt)-bl32.dtb ]; then \
				cp -f $(BLD_PATH)/$(1)-$(dt)/fdts/$(dt)-bl32.dtb $(BL32_DEPLOYDIR)/$(dt)-bl32-$(1).dtb ; \
			fi ; \
			if [ -f $(BLD_PATH)/$(1)-$(dt)/bl32/bl32.elf ]; then \
				mkdir -p $(BL32_DEPLOYDIR)/debug ; \
				cp -f $(BLD_PATH)/$(1)-$(dt)/bl32/bl32.elf $(BL32_DEPLOYDIR)/debug/$(3)-bl32-$(2)-$(1).elf ; \
			fi ; \
		fi ; \
	)
	@$(foreach dt, $(if $(TF_A_DEVICETREE),$(TF_A_DEVICETREE),$(TF_A_DEVICETREE_$(1))), \
		if [ -f $(BLD_PATH)/$(1)-$(dt)/fdts/$(dt)-fw-config.dtb ]; then \
			mkdir -p $(FWCONFIG_DEPLOYDIR) ; \
			cp -f $(BLD_PATH)/$(1)-$(dt)/fdts/$(dt)-fw-config.dtb $(FWCONFIG_DEPLOYDIR)/$(dt)-fw-config-$(1).dtb ; \
		fi ; \
	)
	@$(foreach dt, $(if $(TF_A_DEVICETREE),$(TF_A_DEVICETREE),$(TF_A_DEVICETREE_$(1))), \
		if [ -f $(BLD_PATH)/$(1)-$(dt)/bl2/bl2.elf ] ; then \
			cp -f $(BLD_PATH)/$(1)-$(dt)/bl2/bl2.elf $(DEPLOYDIR)/debug/$(3)-bl2-$(2)-$(1).elf ; \
		fi ; \
	)
endef

# Configure overall deploy rules list
deploy-targets := $(foreach config, $(TF_A_CONFIG), $(foreach soc,  stm32mp21  stm32mp23  stm32mp25 , deploy-$(config)-$(soc)))

# Set dependencies list for building all
DEPS = $(deploy-targets)
#DEPS += fip
DEPS += metadata

help:
	@echo
	@echo "TF-A configuration:"
	@echo "  TF_A_CONFIG = $(TF_A_CONFIG)"
	@echo "Config details:"
	@$(foreach config, $(TF_A_CONFIG), $(call tf-configs,$(config)))
	@echo
	@echo "Note that each TF-A configuration settings can be updated through overall or specific config var:"
	@echo "  TF_A_DEVICETREE"
	@echo "  TF_A_EXTRA_OPTFLAGS"
	@echo "  TF_A_BINARY"
	@echo "  TF_A_MAKE_TARGET"
	@echo
	@echo "TF-A features configuration:"
	@echo "  TF_A_ENABLE_BL31 = $(TF_A_ENABLE_BL31) ('1' to generate bl31 binary)"
	@echo "  TF_A_ENABLE_DEBUG_WRAPPER = $(TF_A_ENABLE_DEBUG_WRAPPER) ('1' to generate tf-a for debugging)"
	@echo "  TF_A_ENABLE_FWDDR = $(TF_A_ENABLE_FWDDR) ('1' to generate tf-a ddr firmware for fip ddr)"
	@echo
	@echo "TF-A folder configuration:"
	@echo "  SRC_PATH  = $(SRC_PATH)"
	@echo "  BLD_PATH  = $(BLD_PATH)"
	@echo "  DEPLOYDIR = $(DEPLOYDIR)"
	@echo "  BL31_DEPLOYDIR     = $(DEPLOYDIR)/bl31"
	@echo "  BL32_DEPLOYDIR     = $(DEPLOYDIR)/bl32"
	@echo "  FWCONFIG_DEPLOYDIR = $(DEPLOYDIR)/fwconfig"
	@echo "  FWDDR_DEPLOYDIR    = $(DEPLOYDIR)/ddr"
	@echo
	@echo "FIP configuration:"
	@echo "  Do not forget to set FIP deploydir folders (such as FIP_DEPLOYDIR_ROOT) to provide path to needed binaries"
	@echo
	@echo "METADATA configuration:"
	@echo "  TF_A_METADATA_TOOL_ARGS = $(TF_A_METADATA_TOOL_ARGS)"
	@echo
	@echo "Available targets:"
	@echo "  all      : build TF-A binaries for defined config(s)"
	@echo "  fip      : build FIP binaries"
	@echo "  metadata : build the TF-A metadata binary"
	@echo "  stm32    : build TF-A stm32 binaries"
	@echo "  clean    : clean build directories from generated files"
	@echo

all: $(DEPS)

host_tools:
	@$(MAKE) --no-print-directory -C $(SRC_PATH)/tools/stm32image

# Set TF-A make rules
$(foreach config, $(TF_A_CONFIG), \
	$(foreach soc,  stm32mp21  stm32mp23  stm32mp25 , \
		$(eval $(call tf-rules,$(config),$(soc),host_tools))))

# Set TF-A deploy rules
$(foreach config, $(TF_A_CONFIG), \
	$(foreach soc,  stm32mp21  stm32mp23  stm32mp25 , \
		$(eval $(call deploy-rules,$(config),$(soc),$(if $(TF_A_BINARY),$(TF_A_BINARY),$(TF_A_BINARY_$(config)))))))

fip: $(deploy-targets)
	for config in $(TF_A_CONFIG) ; do \
		for fipconfig in $(FIP_CONFIG) ; do \
			if [ "$$config" = "$$fipconfig" ]; then \
				FIP_DEPLOYDIR_TFA=$(BL32_DEPLOYDIR) FIP_DEPLOYDIR_BL31=$(BL31_DEPLOYDIR) FIP_DEPLOYDIR_FWCONF=$(FWCONFIG_DEPLOYDIR) FIP_DEPLOYDIR_FWDDR=$(FWDDR_DEPLOYDIR) FIP_CONFIG="$$fipconfig" FIP_BL31_ENABLE="$(TF_A_ENABLE_BL31)" $(if $(TF_A_DEVICETREE),FIP_DEVICETREE="$(TF_A_DEVICETREE)") $(FIPTOOLDIR)/fiptool-stm32mp || exit 1; \
			fi ; \
		done ; \
	done

stm32: $(deploy-targets)

metadata:
	@mkdir -p $(DEPLOYDIR)
	mkfwumdata -g -i 1 -b 2 -v 2 8a7a84a0-8387-40f6-ab41-a8b9a5a60d23,19d5df83-11b0-457b-be2c-7559c13142a5,4fd84c93-54ef-463f-a7ef-ae25ff887087,09c54952-d5bf-45af-acee-335303766fb3 $(DEPLOYDIR)/metadata.bin

clean:
	@for config in $(TF_A_CONFIG) ; do \
		for soc in  stm32mp21  stm32mp23  stm32mp25 ; do \
			echo "Removing $(BLD_PATH)/$$config-$$soc ..." ; \
			rm -rf $(BLD_PATH)/$$config-$$soc* ; \
		done ; \
	done
	@echo "Removing $(DEPLOYDIR) ..."
	@rm -rf $(DEPLOYDIR)
	@echo
